### ISSUE TITLE
Unable to actually see things in-browser as you code along

### ISSUE THREAD

**Issue by AudreyJones** [learn-co-curriculum/model-class-methods-reading#10]
You can't actually test or see any of this in-browser until you complete the last three steps of the code-along....which makes it impossible to follow along with the instructions (seeing things before and after re-factoring).

**Comment by darrendaz** [comment]
You can update the config/routes.rb with your resources so you can follow along in the browser
```
Rails.application.routes.draw do
  resources :posts, :authors
end
```
Should probably be mentioned in the instructions or done for you, rather than having to create them yourself since it's a code along.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
