### ISSUE TITLE
Y No Routes Doh? 

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/model-class-methods-reading#11]
You can't follow along unless you add this code to config/routes.rb: 
```
Rails.application.routes.draw do
  resources :posts, :authors
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
