### ISSUE TITLE
No routes configured in this readme follow along lab...

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/model-class-methods-reading#12]
It's minor but the config/routes file didn't have **resources :posts, :authors** in it so it won't run as instructed until that is added.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
