### ISSUE TITLE
error in file name reference

### ISSUE THREAD

**Issue by SallyZ12** [learn-co-curriculum/model-class-methods-reading#8]
In REFACTORING DATABASE LOGIC OUT OF THE CONTROLLER - the section related to adding the Date Filter in the Model -- the comment for the file name is incorrect for the model.
It is listed as #app/models/posts.rb rather than app/models/post.rb.

The plural is used rather than the singular form for the model name.

This is a small point, but we should be accurate.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @SallyZ12.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
